### ISSUE TITLE
How to make KF ahead predictions when no detection is associated to a track? 

### ISSUE THREAD

**Issue by akbarali2019** [mikel-brostrom/Yolov5_StrongSORT_OSNet#368]
Aprrecieated if anyone could help. I want to implement kalman filter to predict next movement of the detected object. I am a new in this field, so any help would be life saving. It seems, here deepSort is not tracking for next predicition, it is only tracking the detected object. 
For example, imagine objects in 1,2,3,4 7, frames are detected and tracked among 10 frames. How can we predict the localization of the objects in 5,6,8,9,10 frames which werenot detected or tracked?

**Comment by mikel-brostrom** [comment]
In my opinion, the natural thing to do here would be to make a prediction ahead:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/680062c8221c6a247f319dee7ec36537329ca6e1/deep_sort/deep_sort.py#L69

then find the unmatched tracks:

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/680062c8221c6a247f319dee7ec36537329ca6e1/deep_sort/sort/tracker.py#L79

`self.tracks[track_idx]` and extract the kf estimated position by

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/7eb169e6a1810f6067076ab41083e916b864ed12/deep_sort/sort/track.py#L100

and add those to the detections tensor feeded to `tracker.update`

https://github.com/mikel-brostrom/Yolov5_DeepSort_Pytorch/blob/7eb169e6a1810f6067076ab41083e916b864ed12/deep_sort/deep_sort.py#L38

so that tracks gets updated with their own predictions. Feel free to leave a PR for this!

**Comment by akbarali2019** [comment]
Great, @mikel-brostrom. This would be a key to find the solution. But anyway, anyone who can do this, please share your knowledge here. I will also try to manage these lines, but It seems it is more comlex. Thank you

**Comment by A-Fares** [comment]
Hi @mikel-brostrom, I wanna ask how can I use this step "extract the kf estimated position by...."

**Comment by A-Fares** [comment]
I want to check my point to be at the same point when I extract the kf estimated position for the unmatched tracks. it was inside the update function itself. you said at the end we should pass the predicted boxed for the unmatched tracks by adding them to the detection tensor, again to the update function !!

I get struggled with how to add the prediction box to the detection tensor while the tensor needs to extract features based on the original image and so on...

**Comment by mikel-brostrom** [comment]
> it was inside the update function itself. you said at the end we should pass the predicted boxed for the unmatched tracks by adding them to the detection tensor, again to the update function !!

Nobody said it was easy. Some refactoring is definitely needed.
