### ISSUE TITLE
How to deal with the error `No module named 'torchreid'

### ISSUE THREAD

**Issue by YuEn-git** [mikel-brostrom/Yolov5_StrongSORT_OSNet#399]
Hi, I cannot install the package through `pip install torchreid` and I cannot find it in pytorch.org.I cannot solve it for a few hours.

**Comment by mikel-brostrom** [comment]
You have not cloned the repo correctly. Check the Readme

**Comment by ZePinto99** [comment]
I have the same problem. I ran the "**git clone --recurse-submodules https://github.com/mikel-brostrom/Yolov5_DeepSort_OSNet.git**" and "**pip install -r requirements.txt**" commands in a conda environment with Python 3.9.12, Pythorch 1.11.0 and I'm having the same error message when trying to run the tracker.

**Comment by MrXandbadas** [comment]
I had to install

gdown
edict

manually using a venv on windows10 to get it operational

**Comment by YuEn-git** [comment]
> You have not cloned the repo correctly. Check the Readme

I have solved it by cloned the repo again.Thanks for your help!

**Comment by mikel-brostrom** [comment]
> I had to install
> 
> gdown
> edict
> 
> manually using a venv

Does `pip install -r` fail on windows for easydict and gdown @MrXandbadas?

**Comment by MrXandbadas** [comment]
I believe it did
@mikel-brostrom 
Would you accept a Pull Request if I added Docker Support? xD

**Comment by liuliu408** [comment]
git clone https://github.com/KaiyangZhou/deep-person-reid.git
cd deep-person-reid/
python setup.py develop

**Comment by louis-ng1127** [comment]
I met the same issue.

In feature_extractor.py. there is an unresolved reference 'torchreid', so that fail to 
from torchreid.utils import (
    check_isfile, load_pretrained_weights, compute_model_complexity
)
from torchreid.models import build_model

Traceback (most recent call last):
  File "/root/autodl-tmp/Chapter-4/Yolov5_StrongSORT_OSNet/track.py", line 30, in <module>
    from yolov5.models.common import DetectMultiBackend
  File "/root/autodl-tmp/Chapter-4/Yolov5_StrongSORT_OSNet/yolov5/models/common.py", line 24, in <module>
    from utils.dataloaders import exif_transpose, letterbox
  File "/root/autodl-tmp/Chapter-4/Yolov5_StrongSORT_OSNet/strong_sort/deep/reid/torchreid/utils/__init__.py", line 10, in <module>
    from .feature_extractor import FeatureExtractor
  File "/root/autodl-tmp/Chapter-4/Yolov5_StrongSORT_OSNet/strong_sort/deep/reid/torchreid/utils/feature_extractor.py", line 7, in <module>
    from torchreid.utils import (
ModuleNotFoundError: No module named 'torchreid'

**Comment by mikel-brostrom** [comment]
@louis-ng1127, update the repo. Their is no `feature_extractor.py` file anymore

**Comment by nbvictory** [comment]
> > You have not cloned the repo correctly. Check the Readme
> 
> I have solved it by cloning the repo again.Thanks for your help!

请问您怎么解决的
