### ISSUE TITLE
Train Your own dataset?

### ISSUE THREAD

**Issue by PuristWu** [mikel-brostrom/Yolov5_StrongSORT_OSNet#404]
How do I train the model on my own dataset?

**Comment by jgomeher83** [comment]
I Have the same question here!

**Comment by hagiben** [comment]
I think that you may train it in advance and generate your own weights, then simple point the directory of the generated weights into the yolo_model field.

**Comment by mikel-brostrom** [comment]
Which model? Yolov5 or OSNet? Either way, check this link for Yolo: https://github.com/ultralytics/yolov5/wiki/Train-Custom-Data and this link for OSNet: https://kaiyangzhou.github.io/deep-person-reid/user_guide.html

**Comment by quizliu** [comment]
For the weights you can save your own trained weights file and pass them in the commmand line arguments. Also yolov5 supports training with customized objects(your own yaml file in yolov5/data/xxx.yaml). Since track.py doesn't accept a 'data' argument like yolov5, I think adding one in your code is applicable. Or you can change the default value of 'data' argument in yolov5/detect.py to your own yaml file. I am using the second method and it works.
