### ISSUE TITLE
WINDOWS: No URL associated to the chosen DeepSort weights. 

### ISSUE THREAD

**Issue by M-Key4151** [mikel-brostrom/Yolov5_StrongSORT_OSNet#443]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

Greetings. I encountered a small error (rather, my knowledge is not enough:(   ). When starting the program, the following error occurs: "No URL associated to the chosen DeepSort weights. Choose between:"
How to choose? Where? Why and why?
Thanks a lot in advance!

**Comment by mikel-brostrom** [comment]
> How to choose?

```bash
python3 track.py --deep-sort-weights <your-ds-model>
```

> Where?

If the argument is not among the available weights or points to existing weights you will get:

```bash
Available ReID models for automatic download
['resnet50_market1501', 'resnet50_dukemtmcreid', 'resnet50_msmt17', 'resnet50_fc512_market1501', 'resnet50_fc512_dukemtmcreid', 'resnet50_fc512_msmt17', 'mlfn_market1501', 'mlfn_dukemtmcreid', 'mlfn_msmt17', 'hacnn_market1501', 'hacnn_dukemtmcreid', 'hacnn_msmt17', 'mobilenetv2_x1_0_market1501', 'mobilenetv2_x1_0_dukemtmcreid', 'mobilenetv2_x1_0_msmt17', 'mobilenetv2_x1_4_market1501', 'mobilenetv2_x1_4_dukemtmcreid', 'mobilenetv2_x1_4_msmt17', 'osnet_x1_0_market1501', 'osnet_x1_0_dukemtmcreid', 'osnet_x1_0_msmt17', 'osnet_x0_75_market1501', 'osnet_x0_75_dukemtmcreid', 'osnet_x0_75_msmt17', 'osnet_x0_5_market1501', 'osnet_x0_5_dukemtmcreid', 'osnet_x0_5_msmt17', 'osnet_x0_25_market1501', 'osnet_x0_25_dukemtmcreid', 'osnet_x0_25_msmt17', 'resnet50_MSMT17', 'osnet_x1_0_MSMT17', 'osnet_x0_75_MSMT17', 'osnet_x0_5_MSMT17', 'osnet_x0_25_MSMT17', 'osnet_ibn_x1_0_MSMT17', 'osnet_ain_x1_0_MSMT17']
```

All of these are available for automatic download. If you want to know more abut the models check: https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO

> Why?

Depends on your needs. Need something that runs fast on CPU will a bit less ReID accuracy, try the mobilenet models; want maximum tracking accuracy on GPU with maximum ReID accuracy, try one of the larger OSNet modes.

**Comment by M-Key4151** [comment]
I was able to run the code, but only with --strong-sort-weights. What do I need to do to run the code with  --yolo-weights yolov5n.pt? If I enter such a command "python track.py --source 0 --yolo-weights yolov5n.pt --img 640". I'm getting an error

**Comment by mikel-brostrom** [comment]
Post the error, please

**Comment by M-Key4151** [comment]
No URL associated to the chosen DeepSort weights. Choose between:

**Comment by mikel-brostrom** [comment]
Check again, you command cannot be

`python track.py --source 0 --yolo-weights yolov5n.pt --img 640`

if the error you get is 

```
No URL associated to the chosen DeepSort weights
```

Because the default ReID model is available

**Comment by mikel-brostrom** [comment]
Post your complete command that is failing please @CristinaEvangelista

**Comment by CristinaEvangelista** [comment]
The one mentioned in the readme for tracking:

python track.py --source 0 --yolo-weights yolov5/weights/crowdhuman_yolov5m.pt --classes 0  # tracks personal, only

**Comment by mikel-brostrom** [comment]
I have not issue running this command, no issue on CI either:

```
Yolov5_StrongSORT_OSNet git:(master) ✗ python track.py --source 0 --yolo-weights yolov5/weights/yolov5m.pt --classes 0
strong_sort/deep/reid/torchreid/metrics/rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(
track: yolo_weights=['yolov5/weights/yolov5m.pt'], strong_sort_weights=/path/to/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.pt, config_strongsort=strong_sort/configs/strong_sort.yaml, source=0, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_vid=False, nosave=False, classes=[0], agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/track, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False
YOLOv5 🚀 2022-7-12 Python-3.8.0 torch-1.12.0+cu102 CUDA:0 (Quadro P2000, 4032MiB)

Fusing layers... 
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients
1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

Model: osnet_x0_25
- params: 203,568
- flops: 82,316,000
Successfully loaded pretrained weights from "/path/to/Yolov5_StrongSORT_OSNet/weights/osnet_x0_25_msmt17.pt"
** The following layers are discarded due to unmatched keys or layer size: ['classifier.weight', 'classifier.bias']
0: 480x640 2 persons, Done. YOLO:(1.095s), StrongSORT:(0.100s)
0: 480x640 2 persons, Done. YOLO:(0.038s), StrongSORT:(0.016s)
0: 480x640 2 persons, Done. YOLO:(0.040s), StrongSORT:(0.015s)
0: 480x640 2 persons, Done. YOLO:(0.040s), StrongSORT:(0.015s)
0: 480x640 1 person, Done. YOLO:(0.039s), StrongSORT:(0.052s)
```

Pull the latest please

**Comment by cri30** [comment]
Command: python track.py --source 0 --yolo-weights yolov5m.pt --classes 0


Results: 

C:\Yolov5_StrongSORT_OSNet\strong_sort/deep/reid\torchreid\metrics\rank.py:11: UserWarning: Cython evaluation (very fast so highly recommended) is unavailable, now use python evaluation.
  warnings.warn(
track: yolo_weights=['yolov5m.pt'], strong_sort_weights=C:\Yolov5_StrongSORT_OSNet\weights\osnet_x0_25_msmt17.pt, config_strongsort=strong_sort/configs/strong_sort.yaml, source=0, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_vid=False, nosave=False, classes=[0], agnostic_nms=False, augment=False, visualize=False, update=False, project=runs\track, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False
YOLOv5  2022-7-20 Python-3.9.13 torch-1.12.0+cpu CPU

Fusing layers...
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients
1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

No URL associated to the chosen DeepSort weights. Choose between:

Available ReID models for automatic download
['resnet50_market1501.pt', 'resnet50_dukemtmcreid.pt', 'resnet50_msmt17.pt', 'resnet50_fc512_market1501.pt', 'resnet50_fc512_dukemtmcreid.pt', 'resnet50_fc512_msmt17.pt', 'mlfn_market1501.pt', 'mlfn_dukemtmcreid.pt', 'mlfn_msmt17.pt', 'hacnn_market1501.pt', 'hacnn_dukemtmcreid.pt', 'hacnn_msmt17.pt', 'mobilenetv2_x1_0_market1501.pt', 'mobilenetv2_x1_0_dukemtmcreid.pt', 'mobilenetv2_x1_0_msmt17.pt', 'mobilenetv2_x1_4_market1501.pt', 'mobilenetv2_x1_4_dukemtmcreid.pt', 'mobilenetv2_x1_4_msmt17.pt', 'osnet_x1_0_market1501.pt', 'osnet_x1_0_dukemtmcreid.pt', 'osnet_x1_0_msmt17.pt', 'osnet_x0_75_market1501.pt', 'osnet_x0_75_dukemtmcreid.pt', 'osnet_x0_75_msmt17.pt', 'osnet_x0_5_market1501.pt', 'osnet_x0_5_dukemtmcreid.pt', 'osnet_x0_5_msmt17.pt', 'osnet_x0_25_market1501.pt', 'osnet_x0_25_dukemtmcreid.pt', 'osnet_x0_25_msmt17.pt', 'osnet_ibn_x1_0_msmt17.pt', 'osnet_ain_x1_0_msmt17.pt']

**Comment by cri30** [comment]
As mentioned by @M-Key4151, as soon as the command focuses on the --yolo-weights, the "No URL" error comes up.

**Comment by mikel-brostrom** [comment]
I see you are working on a windows machine. This software has never been tested on windows. As I don't own a windows machine I cannot help you debug either. Sorry

**Comment by mikel-brostrom** [comment]
If you fix it let me know and feel free to submit a PR

**Comment by silvanro** [comment]
You also have to give strong-sort-weights. I had the same issue but the following works:

python track.py --source 0 --strong-sort-weights osnet_x0_25_market1501.pt --yolo-weights yolov5m.pt --classes 0

**Comment by HooradAboo** [comment]
Hello everyone,

I have the same problem. It seems the main problem is because of the internet connection. But I have no idea how to solve it.

This is the command:
`python track.py --yolo-weights weights/yolov5m.pt --strong-sort-weights weights/osnet_x0_25_msmt17.pt`

and this is the error:
`yolo_weights=['weights/yolov5m.pt'], strong_sort_weights=weights/osnet_x0_25_msmt17.pt, config_strongsort=strong_sort/configs/strong_sort.yaml, source=0, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_vid=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/track, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False
Python 3.7.0 required by YOLOv5, but Python 3.6.9 is currently installed
YOLOv5 🚀 2022-7-26 Python-3.6.9 torch-1.10.1+cu102 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 7981MiB)

Fusing layers... 
YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients, 49.0 GFLOPs
QObject::moveToThread: Current thread (0x8bfe6670) is not the object's thread (0x8dec6340).
Cannot move to target thread (0x8bfe6670)

QObject::moveToThread: Current thread (0x8bfe6670) is not the object's thread (0x8dec6340).
Cannot move to target thread (0x8bfe6670)

1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)

Traceback (most recent call last):
  File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
    (self._dns_host, self.port), self.timeout, **extra_kw
  File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 95, in create_connection
    raise err
  File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 85, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
    chunked=chunked,
  File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
    self._validate_conn(conn)
  File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
    conn.connect()
  File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
    self.sock = conn = self._new_conn()
  File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
    self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd849cb4128>: Failed to establish a new connection: [Errno 111] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/hoorad/.local/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
    timeout=timeout
  File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
    method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
  File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='doc-08-b4-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6pn1cu6gljl9avsbo5s2dgq4cjh3qfha/1658853225000/01683402606086414038/*/1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e?uuid=9e1baf33-9480-4369-8240-c682d212d81f (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd849cb4128>: Failed to establish a new connection: [Errno 111] Connection refused',))

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "track.py", line 321, in <module>
    main(opt)
  File "track.py", line 316, in main
    run(**vars(opt))
  File "/home/hoorad/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
    return func(*args, **kwargs)
  File "track.py", line 128, in run
    ema_alpha=cfg.STRONGSORT.EMA_ALPHA,
  File "/home/hoorad/Desktop/Yolov5_StrongSORT_OSNet/strong_sort/strong_sort.py", line 32, in __init__
    gdown.download(model_url, str(model_weights), quiet=False)
  File "/home/hoorad/.local/lib/python3.6/site-packages/gdown/download.py", line 146, in download
    res = sess.get(url, headers=headers, stream=True, verify=verify)
  File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in get
    return self.request('GET', url, **kwargs)
  File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 667, in send
    history = [resp for resp in gen]
  File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 667, in <listcomp>
    history = [resp for resp in gen]
  File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 245, in resolve_redirects
    **adapter_kwargs
  File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
    r = adapter.send(request, **kwargs)
  File "/home/hoorad/.local/lib/python3.6/site-packages/requests/adapters.py", line 519, in send
    raise ConnectionError(e, request=request)
requests.exceptions.ConnectionError: HTTPSConnectionPool(host='doc-08-b4-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6pn1cu6gljl9avsbo5s2dgq4cjh3qfha/1658853225000/01683402606086414038/*/1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e?uuid=9e1baf33-9480-4369-8240-c682d212d81f (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd849cb4128>: Failed to establish a new connection: [Errno 111] Connection refused',))`

I also tried to find osnet_x0_25_msmt17.pt and download it manually, but I cannot find it in this website:
https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO

Is there any place to download one of these weights?
`Available ReID models for automatic download
['resnet50_market1501.pt', 'resnet50_dukemtmcreid.pt', 'resnet50_msmt17.pt', 'resnet50_fc512_market1501.pt', 'resnet50_fc512_dukemtmcreid.pt', 'resnet50_fc512_msmt17.pt', 'mlfn_market1501.pt', 'mlfn_dukemtmcreid.pt', 'mlfn_msmt17.pt', 'hacnn_market1501.pt', 'hacnn_dukemtmcreid.pt', 'hacnn_msmt17.pt', 'mobilenetv2_x1_0_market1501.pt', 'mobilenetv2_x1_0_dukemtmcreid.pt', 'mobilenetv2_x1_0_msmt17.pt', 'mobilenetv2_x1_4_market1501.pt', 'mobilenetv2_x1_4_dukemtmcreid.pt', 'mobilenetv2_x1_4_msmt17.pt', 'osnet_x1_0_market1501.pt', 'osnet_x1_0_dukemtmcreid.pt', 'osnet_x1_0_msmt17.pt', 'osnet_x0_75_market1501.pt', 'osnet_x0_75_dukemtmcreid.pt', 'osnet_x0_75_msmt17.pt', 'osnet_x0_5_market1501.pt', 'osnet_x0_5_dukemtmcreid.pt', 'osnet_x0_5_msmt17.pt', 'osnet_x0_25_market1501.pt', 'osnet_x0_25_dukemtmcreid.pt', 'osnet_x0_25_msmt17.pt', 'osnet_ibn_x1_0_msmt17.pt', 'osnet_ain_x1_0_msmt17.pt']`

I would appreciate it if you could answer it.

**Comment by 2351548518** [comment]
I have the same problem.I find that the file in ```strong_sort/deep/checkpoint``` is same than osnet_x0_5_market1501.pt also.so I modify the file from .pth to .pt,I find is same,and is useful.

**Comment by 2351548518** [comment]
You also can use ```pip install urllib3==1.25.11``` to fixed the ERROR like that.
```
(Caused by SSLError(SSLEOFError(8, ‘EOF occurred in violation of protocol (_ssl.c:1129)’
```
but you should then update urllib3 next.I think is not a good way.

**Comment by 2351548518** [comment]
> Hello everyone,
> 
> I have the same problem. It seems the main problem is because of the internet connection. But I have no idea how to solve it.
> 
> This is the command that I run: `python track.py --yolo-weights weights/yolov5m.pt --strong-sort-weights weights/osnet_x0_25_msmt17.pt`
> 
> and this is the error:
> 
> ```
> yolo_weights=['weights/yolov5m.pt'], strong_sort_weights=weights/osnet_x0_25_msmt17.pt, config_strongsort=strong_sort/configs/strong_sort.yaml, source=0, imgsz=[640, 640], conf_thres=0.5, iou_thres=0.5, max_det=1000, device=, show_vid=False, save_txt=False, save_conf=False, save_crop=False, save_vid=False, nosave=False, classes=None, agnostic_nms=False, augment=False, visualize=False, update=False, project=runs/track, name=exp, exist_ok=False, line_thickness=3, hide_labels=False, hide_conf=False, hide_class=False, half=False, dnn=False
> Python 3.7.0 required by YOLOv5, but Python 3.6.9 is currently installed
> YOLOv5 🚀 2022-7-26 Python-3.6.9 torch-1.10.1+cu102 CUDA:0 (NVIDIA GeForce RTX 2060 SUPER, 7981MiB)
> 
> Fusing layers... 
> YOLOv5m summary: 290 layers, 21172173 parameters, 0 gradients, 49.0 GFLOPs
> QObject::moveToThread: Current thread (0x8bfe6670) is not the object's thread (0x8dec6340).
> Cannot move to target thread (0x8bfe6670)
> 
> QObject::moveToThread: Current thread (0x8bfe6670) is not the object's thread (0x8dec6340).
> Cannot move to target thread (0x8bfe6670)
> 
> 1/1: 0...  Success (inf frames 640x480 at 30.00 FPS)
> 
> Traceback (most recent call last):
>   File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connection.py", line 175, in _new_conn
>     (self._dns_host, self.port), self.timeout, **extra_kw
>   File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 95, in create_connection
>     raise err
>   File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/util/connection.py", line 85, in create_connection
>     sock.connect(sa)
> ConnectionRefusedError: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 710, in urlopen
>     chunked=chunked,
>   File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 386, in _make_request
>     self._validate_conn(conn)
>   File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 1040, in _validate_conn
>     conn.connect()
>   File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connection.py", line 358, in connect
>     self.sock = conn = self._new_conn()
>   File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connection.py", line 187, in _new_conn
>     self, "Failed to establish a new connection: %s" % e
> urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd849cb4128>: Failed to establish a new connection: [Errno 111] Connection refused
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/home/hoorad/.local/lib/python3.6/site-packages/requests/adapters.py", line 450, in send
>     timeout=timeout
>   File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/connectionpool.py", line 786, in urlopen
>     method, url, error=e, _pool=self, _stacktrace=sys.exc_info()[2]
>   File "/home/hoorad/.local/lib/python3.6/site-packages/urllib3/util/retry.py", line 592, in increment
>     raise MaxRetryError(_pool, url, error or ResponseError(cause))
> urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='doc-08-b4-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6pn1cu6gljl9avsbo5s2dgq4cjh3qfha/1658853225000/01683402606086414038/*/1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e?uuid=9e1baf33-9480-4369-8240-c682d212d81f (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd849cb4128>: Failed to establish a new connection: [Errno 111] Connection refused',))
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "track.py", line 321, in <module>
>     main(opt)
>   File "track.py", line 316, in main
>     run(**vars(opt))
>   File "/home/hoorad/.local/lib/python3.6/site-packages/torch/autograd/grad_mode.py", line 28, in decorate_context
>     return func(*args, **kwargs)
>   File "track.py", line 128, in run
>     ema_alpha=cfg.STRONGSORT.EMA_ALPHA,
>   File "/home/hoorad/Desktop/Yolov5_StrongSORT_OSNet/strong_sort/strong_sort.py", line 32, in __init__
>     gdown.download(model_url, str(model_weights), quiet=False)
>   File "/home/hoorad/.local/lib/python3.6/site-packages/gdown/download.py", line 146, in download
>     res = sess.get(url, headers=headers, stream=True, verify=verify)
>   File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 542, in get
>     return self.request('GET', url, **kwargs)
>   File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 529, in request
>     resp = self.send(prep, **send_kwargs)
>   File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 667, in send
>     history = [resp for resp in gen]
>   File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 667, in <listcomp>
>     history = [resp for resp in gen]
>   File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 245, in resolve_redirects
>     **adapter_kwargs
>   File "/home/hoorad/.local/lib/python3.6/site-packages/requests/sessions.py", line 645, in send
>     r = adapter.send(request, **kwargs)
>   File "/home/hoorad/.local/lib/python3.6/site-packages/requests/adapters.py", line 519, in send
>     raise ConnectionError(e, request=request)
> requests.exceptions.ConnectionError: HTTPSConnectionPool(host='doc-08-b4-docs.googleusercontent.com', port=443): Max retries exceeded with url: /docs/securesc/ha0ro937gcuc7l7deffksulhg5h7mbp1/6pn1cu6gljl9avsbo5s2dgq4cjh3qfha/1658853225000/01683402606086414038/*/1Kkx2zW89jq_NETu4u42CFZTMVD5Hwm6e?uuid=9e1baf33-9480-4369-8240-c682d212d81f (Caused by NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fd849cb4128>: Failed to establish a new connection: [Errno 111] Connection refused',))
> ```
> 
> I also tried to find osnet_x0_25_msmt17.pt and download it manually, but I cannot find it in this website: https://kaiyangzhou.github.io/deep-person-reid/MODEL_ZOO
> 
> Is there any place to download one of these weights?
> 
> ```
> Available ReID models for automatic download
> ['resnet50_market1501.pt', 'resnet50_dukemtmcreid.pt', 'resnet50_msmt17.pt', 'resnet50_fc512_market1501.pt', 'resnet50_fc512_dukemtmcreid.pt', 'resnet50_fc512_msmt17.pt', 'mlfn_market1501.pt', 'mlfn_dukemtmcreid.pt', 'mlfn_msmt17.pt', 'hacnn_market1501.pt', 'hacnn_dukemtmcreid.pt', 'hacnn_msmt17.pt', 'mobilenetv2_x1_0_market1501.pt', 'mobilenetv2_x1_0_dukemtmcreid.pt', 'mobilenetv2_x1_0_msmt17.pt', 'mobilenetv2_x1_4_market1501.pt', 'mobilenetv2_x1_4_dukemtmcreid.pt', 'mobilenetv2_x1_4_msmt17.pt', 'osnet_x1_0_market1501.pt', 'osnet_x1_0_dukemtmcreid.pt', 'osnet_x1_0_msmt17.pt', 'osnet_x0_75_market1501.pt', 'osnet_x0_75_dukemtmcreid.pt', 'osnet_x0_75_msmt17.pt', 'osnet_x0_5_market1501.pt', 'osnet_x0_5_dukemtmcreid.pt', 'osnet_x0_5_msmt17.pt', 'osnet_x0_25_market1501.pt', 'osnet_x0_25_dukemtmcreid.pt', 'osnet_x0_25_msmt17.pt', 'osnet_ibn_x1_0_msmt17.pt', 'osnet_ain_x1_0_msmt17.pt']
> ```
> 
> I would appreciate it if you could answer it.

I have the same problem.I find that the file in strong_sort/deep/checkpoint is same than osnet_x0_5_market1501.pt also.so I modify the file from .pth to .pt,I find is same,and is useful.
