### ISSUE TITLE
I use a single image as source and ended up with a video

### ISSUE THREAD

**Issue by songjiahao-wq** [mikel-brostrom/Yolov5_StrongSORT_OSNet#512]
### Search before asking

- [X] I have searched the Yolov5_StrongSORT_OSNet [issues](https://github.com/mikel-brostrom/Yolov5_StrongSORT_OSNet/issues) and found no similar bug report.

### Question

I used python track.py --source yolov5/data/images --save-vid. Why is the final result in video format
![image](https://user-images.githubusercontent.com/75210061/187817635-3a95f46d-c12a-48eb-9b48-624fcdc7d5e8.png)

In addition, I read the source code and believe that your original intention here is to name the reasoning result after the file name. However, when you enter the file directory containing the video, the previous reasoning result will be overwritten constantly and only the last reasoning video will be saved.
![image](https://user-images.githubusercontent.com/75210061/187817846-695a434e-f19f-4dc7-8615-16e949dd69dc.png)

**Comment by mikel-brostrom** [comment]
It makes no sense to run a tracker on a single images more than for checking if the tracker is running (as in the CI pipeline). This is because the idea with tracking is to input a sequences of images and associate current detection to previously identified objects in previous frames. If you want to detect objects in single images, which seems to be what you want to achieve, then go for yolov5's `detect.py`
